spring.application.name=Calculator-Application

#PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/practice01
spring.datasource.username=postgres
spring.datasource.password=root

#Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#port configuration
server.port=4041
